"""Create tables users, addresses, medicals

Revision ID: b5ca47689d0a
Revises: 
Create Date: 2024-06-27 17:33:05.894119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ca47689d0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('middlename', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('dateofbirth', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('hispanic', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('physicaladdress', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('physicalcounty', sa.String(), nullable=True),
    sa.Column('physicalstate', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facilityname', sa.String(), nullable=False),
    sa.Column('facilitycity', sa.String(), nullable=True),
    sa.Column('facilitycounty', sa.String(), nullable=True),
    sa.Column('facilitystate', sa.String(), nullable=True),
    sa.Column('phonenumber', sa.Integer(), nullable=False),
    sa.Column('medicalrecord', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicals')
    op.drop_table('addresses')
    op.drop_table('users')
    # ### end Alembic commands ###
